// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsMw4Yz_2Y2a7eYM7lN8uUENks6k5Q56g',
    appId: '1:796226080366:web:bcaa58052cc7df3931e07f',
    messagingSenderId: '796226080366',
    projectId: 'dressmaker-app',
    authDomain: 'dressmaker-app.firebaseapp.com',
    storageBucket: 'dressmaker-app.firebasestorage.app',
    measurementId: 'G-LE868RZ5K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJWhRhKK9Eu_lYjLVXxlQxzpBKEsbT7Sw',
    appId: '1:796226080366:android:23d8c842e3b2ab2031e07f',
    messagingSenderId: '796226080366',
    projectId: 'dressmaker-app',
    storageBucket: 'dressmaker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqF_93tDn2sko8UfB77QSHXA_Mk3iYVGQ',
    appId: '1:796226080366:ios:912e82bfea588f1331e07f',
    messagingSenderId: '796226080366',
    projectId: 'dressmaker-app',
    storageBucket: 'dressmaker-app.firebasestorage.app',
    iosBundleId: 'com.example.clothingStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqF_93tDn2sko8UfB77QSHXA_Mk3iYVGQ',
    appId: '1:796226080366:ios:912e82bfea588f1331e07f',
    messagingSenderId: '796226080366',
    projectId: 'dressmaker-app',
    storageBucket: 'dressmaker-app.firebasestorage.app',
    iosBundleId: 'com.example.clothingStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsMw4Yz_2Y2a7eYM7lN8uUENks6k5Q56g',
    appId: '1:796226080366:web:d260c171bf4326be31e07f',
    messagingSenderId: '796226080366',
    projectId: 'dressmaker-app',
    authDomain: 'dressmaker-app.firebaseapp.com',
    storageBucket: 'dressmaker-app.firebasestorage.app',
    measurementId: 'G-GJ1Y65L9KD',
  );
}
